apiVersion: v1
kind: Secret

metadata:
  name: smartdesk-secret
  namespace: smartdesk

type: Opaque

stringData:
  APP_KEY: "base64:mEDIPh7Tbvpn1FIs6BKwjPT9cSSSxUAHPUOsymmpfvQ"
  DB_PASSWORD: ""

  MAIL_USERNAME: "trishahingu2406@gmail.com"
  MAIL_PASSWORD: "ydxfnxgmiaysfvcm"

  GEMINI_API_KEY: "your-gemini-api-key"