name: Trigger GitHub Actions

on:
  push:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
        php-version: '8.3'

      - name: Install Dependencies
        run: composer install --no-interaction

      - name: Copy Environment
        run: |
          if [ -f .env.example ]; then
            cp .env.example .env
          fi

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test